# Generated by Django 4.2.10 on 2024-03-11 05:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('TechEdu', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='itemdetails',
            name='qty',
        ),
    ]
