# Generated by Django 4.2.10 on 2024-03-11 09:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TechEdu', '0004_cart_image_cart_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart',
            name='itemsid',
            field=models.CharField(default=2, max_length=50),
            preserve_default=False,
        ),
    ]
